[package]
name = "artificial-life-explorer"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.1"
bevy_egui = "0.24.0"
rand = "0.8.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
